services:
  mariadb:
    container_name: tl_db
    image: 'docker.io/bitnami/mariadb:10.5'
    restart: always
    environment:
      - MARIADB_USER=testlink
      - MARIADB_DATABASE=testlink
      - MARIADB_PASSWORD=${TL_DB_PASSWORD}
      - MARIADB_CHARACTER_SET=utf8mb4
      - MARIADB_COLLATE=utf8mb4_general_ci
      - MARIADB_ROOT_PASSWORD=${TL_ROOT_PASSWORD}
    volumes:
      - '/srv/testlink/mariadb:/bitnami/mariadb'
  web:
    container_name: tl_web
    image: 'docker.io/bitnami/testlink:latest'
    restart: always
    ports:
        - '127.0.0.1:48080:8080/tcp'
    environment:
      - TESTLINK_USERNAME=testlink
      - TESTLINK_PASSWORD=${TL_APP_PASSWD}
      - TESTLINK_LANGUAGE=zh_CN
      - TESTLINK_DATABASE_USER=testlink
      - TESTLINK_DATABASE_NAME=testlink
      - TESTLINK_DATABASE_PASSWORD=${TL_DB_PASSWORD}
    volumes:
      - '/srv/testlink/tldata:/bitnami/testlink'
      - '/srv/testlink/custom_config.inc.php:/opt/bitnami/testlink/custom_config.inc.php'
      - '/srv/testlink/php.ini:/opt/bitnami/php/etc/php.ini'
    depends_on:
      - mariadb
